[cosmic-ray]
module-path = "catalog"
timeout = 60.0
excluded-modules = ['catalog/infrastructure/**/*.py']
test-command = "../../.venv/Scripts/python.exe -m pytest tests/unit -x -q"

[cosmic-ray.distributor]
name = "local"
